import { MoviesData } from './movie-card';

export const MOCK_DATA: MoviesData['results'] = [
  {
    backdrop_path: '/8uVKfOJUhmybNsVh089EqLHUYEG.jpg',
    id: 693134,
    original_title: 'Dune: Part Two',
    overview:
      'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
    poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Dune: Part Two',
    original_language: 'en',
    genre_ids: [878, 12],
    popularity: 1990.512,
    release_date: '2024-02-27',
    video: false,
    vote_average: 8.263,
    vote_count: 3454,
  },
  {
    backdrop_path: '/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg',
    id: 937287,
    original_title: 'Challengers',
    overview:
      'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
    poster_path: '/H6vke7zGiuLsz4v4RPeReb9rsv.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Challengers',
    original_language: 'en',
    genre_ids: [18, 10749],
    popularity: 531.851,
    release_date: '2024-04-18',
    video: false,
    vote_average: 7.417,
    vote_count: 192,
  },
  {
    backdrop_path: '/2rjI2uXmjitMAaXVO21r9ao7v2j.jpg',
    id: 746036,
    original_title: 'The Fall Guy',
    overview:
      'Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.',
    poster_path: '/vrIcYxZ8288udqTAmui2LL8K0VN.jpg',
    media_type: 'movie',
    adult: false,
    title: 'The Fall Guy',
    original_language: 'en',
    genre_ids: [28, 35, 12],
    popularity: 360.373,
    release_date: '2024-04-24',
    video: false,
    vote_average: 8,
    vote_count: 41,
  },
  {
    backdrop_path: '/lA6KdSkCTxwzvqzPqxch997RabQ.jpg',
    id: 560016,
    original_title: 'Monkey Man',
    overview:
      'Kid is an anonymous young man who ekes out a meager living in an underground fight club where, night after night, wearing a gorilla mask, he is beaten bloody by more popular fighters for cash. After years of suppressed rage, Kid discovers a way to infiltrate the enclave of the city’s sinister elite. As his childhood trauma boils over, his mysteriously scarred hands unleash an explosive campaign of retribution to settle the score with the men who took everything from him.',
    poster_path: '/4lhR4L2vzzjl68P1zJyCH755Oz4.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Monkey Man',
    original_language: 'en',
    genre_ids: [28, 53, 80],
    popularity: 502.284,
    release_date: '2024-04-03',
    video: false,
    vote_average: 7.271,
    vote_count: 258,
  },
  {
    backdrop_path: '/FUnAVgaTs5xZWXcVzPJNxd9qGA.jpg',
    id: 934632,
    original_title: 'Rebel Moon — Part Two: The Scargiver',
    overview:
      'The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.',
    poster_path: '/cxevDYdeFkiixRShbObdwAHBZry.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Rebel Moon — Part Two: The Scargiver',
    original_language: 'en',
    genre_ids: [878, 28, 18, 12],
    popularity: 2477.048,
    release_date: '2024-04-19',
    video: false,
    vote_average: 6.137,
    vote_count: 552,
  },
  {
    backdrop_path: '/vTlK3chwsEToSoQJYUcJaHlNhIf.jpg',
    id: 618588,
    original_title: 'Arthur the King',
    overview:
      'Over the course of ten days and 435 miles, an unbreakable bond is forged between pro adventure racer Michael Light and a scrappy street dog companion dubbed Arthur. As the team is pushed to their outer limits of endurance in the race, Arthur redefines what victory, loyalty and friendship truly mean.',
    poster_path: '/gxVcBc4VM0kAg9wX4HVg6KJHG46.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Arthur the King',
    original_language: 'en',
    genre_ids: [18, 12],
    popularity: 1308.397,
    release_date: '2024-03-15',
    video: false,
    vote_average: 6.707,
    vote_count: 70,
  },
  {
    backdrop_path: '/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg',
    id: 438631,
    original_title: 'Dune',
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    poster_path: '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Dune',
    original_language: 'en',
    genre_ids: [878, 12],
    popularity: 627.288,
    release_date: '2021-09-15',
    video: false,
    vote_average: 7.79,
    vote_count: 11435,
  },
  {
    backdrop_path: '/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg',
    id: 866398,
    original_title: 'The Beekeeper',
    overview:
      "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
    poster_path: '/A7EByudX0eOzlkQ2FIbogzyazm2.jpg',
    media_type: 'movie',
    adult: false,
    title: 'The Beekeeper',
    original_language: 'en',
    genre_ids: [28, 53, 18],
    popularity: 458.009,
    release_date: '2024-01-08',
    video: false,
    vote_average: 7.457,
    vote_count: 2180,
  },
  {
    backdrop_path: '/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg',
    id: 929590,
    original_title: 'Civil War',
    overview:
      'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
    poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Civil War',
    original_language: 'en',
    genre_ids: [10752, 28, 18],
    popularity: 723.121,
    release_date: '2024-04-10',
    video: false,
    vote_average: 7.409,
    vote_count: 485,
  },
  {
    backdrop_path: '/lWMa1FdgC7zP9ATVg6dgpZ3rxhe.jpg',
    id: 762509,
    original_title: 'Mufasa: The Lion King',
    overview:
      'Rafiki relays the legend of Mufasa to lion cub Kiara, daughter of Simba and Nala. Told in flashbacks, the story introduces Mufasa as an orphaned cub, lost and alone until he meets a sympathetic lion named Taka—the heir to a royal bloodline. The chance meeting sets in motion a journey of misfits searching for their destiny and working together to evade a threatening and deadly foe.',
    poster_path: '/9bXHaLlsFYpJUutg4E6WXAjaxDi.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Mufasa: The Lion King',
    original_language: 'en',
    genre_ids: [12, 16, 10751, 10402],
    popularity: 16.709,
    release_date: '2024-12-18',
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    backdrop_path: '/1XDDXPXGiI8id7MrUxK36ke7gkX.jpg',
    id: 1011985,
    original_title: 'Kung Fu Panda 4',
    overview:
      'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.',
    poster_path: '/kDp1vUBnMpe8ak4rjgl3cLELqjU.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Kung Fu Panda 4',
    original_language: 'en',
    genre_ids: [16, 28, 10751, 35, 14],
    popularity: 2020.311,
    release_date: '2024-03-02',
    video: false,
    vote_average: 7.162,
    vote_count: 1382,
  },
  {
    backdrop_path: '/aINel9503ompOlGKn4sIVMg09Un.jpg',
    id: 838209,
    original_title: '파묘',
    overview:
      "After tracing the origin of a disturbing supernatural affliction to a wealthy family's ancestral gravesite, a team of paranormal experts relocates the remains—and soon discovers what happens to those who dare to mess with the wrong grave.",
    poster_path: '/pQYHouPsDw32FhDLr7E3jmw0WTk.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Exhuma',
    original_language: 'ko',
    genre_ids: [9648, 27, 53],
    popularity: 367.942,
    release_date: '2024-02-22',
    video: false,
    vote_average: 7.655,
    vote_count: 58,
  },
  {
    backdrop_path: '/6VoxDupaW2VXfLtJyeOoGCgXSjD.jpg',
    id: 1116490,
    original_title: 'Cash Out',
    overview:
      'Criminal mastermind Mason is about to execute the score of a lifetime when his lover and key member of his crew, Decker, takes the team down and reveals she’s an undercover Interpol agent. Heartbroken, Mason escapes and retires from the life of crime until his younger brother Shawn is out of his league taking on a big bank heist all on his own. Mason has no choice left but to come to the rescue, while Interpol brings Decker in hoping to unnerve him. Before the SWAT teams storm the bank, Mason must use every tool in his arsenal to not only escape with the prize, but also the love of his life.',
    poster_path: '/v3youHDLigrtIis1NqTjlY8Sk38.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Cash Out',
    original_language: 'en',
    genre_ids: [28, 80, 53],
    popularity: 146.361,
    release_date: '2024-04-26',
    video: false,
    vote_average: 6.7,
    vote_count: 14,
  },
  {
    backdrop_path: '/AuTfo1lbE8s2Y8RVTmlbJAeLWPK.jpg',
    id: 850888,
    original_title: 'Sayen: La Cazadora',
    overview:
      "The action-packed thriller follows the journey of Sayen, a Mapuche woman who uncovers a dangerous conspiracy led by an international corporation that is destroying her family's land and ravaging the local ecosystems throughout Chile, and takes it upon herself to bring these people to justice and save her family's legacy.",
    poster_path: '/77a96CjyAZik5QrdgNzObLtmoxb.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Sayen: The Huntress',
    original_language: 'es',
    genre_ids: [28, 53],
    popularity: 83.245,
    release_date: '2024-04-26',
    video: false,
    vote_average: 7.25,
    vote_count: 12,
  },
  {
    backdrop_path: '/8PyV1YsO0ZPHZug9aEe363UUwed.jpg',
    id: 914215,
    original_title: 'Humane',
    overview:
      "In the wake of an environmental collapse that has forced humanity to shed 20% of its population, a family dinner erupts into chaos when a father's plan to enlist in the government's new euthanasia program goes horribly awry.",
    poster_path: '/ecOvKaoM1hwQbp0uTnULGrSV32e.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Humane',
    original_language: 'en',
    genre_ids: [53, 27, 878],
    popularity: 164.517,
    release_date: '2024-04-26',
    video: false,
    vote_average: 5.4,
    vote_count: 15,
  },
  {
    backdrop_path: '/qrGtVFxaD8c7et0jUtaYhyTzzPg.jpg',
    id: 823464,
    original_title: 'Godzilla x Kong: The New Empire',
    overview:
      'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
    poster_path: '/bQ2ywkchIiaKLSEaMrcT6e29f91.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Godzilla x Kong: The New Empire',
    original_language: 'en',
    genre_ids: [28, 878, 12],
    popularity: 2372.572,
    release_date: '2024-03-27',
    video: false,
    vote_average: 6.64,
    vote_count: 798,
  },
  {
    backdrop_path: '/qnVm19Vu2Sc14LoEj82pmqAYr3p.jpg',
    id: 845111,
    original_title: 'Les trois mousquetaires : Milady',
    overview:
      "D'Artagnan, on a quest to rescue the abducted Constance, runs into the mysterious Milady de Winter again. The tension between the Catholics and the Protestants finally escalates, as the king declares war — forcing the now four musketeers into battle. But as the war goes on, they are tested physically, mentally and emotionally.",
    poster_path: '/rtosxP5sXuoRFPH4sVbMccLIPiV.jpg',
    media_type: 'movie',
    adult: false,
    title: 'The Three Musketeers: Milady',
    original_language: 'fr',
    genre_ids: [12, 28, 18],
    popularity: 1352.91,
    release_date: '2023-12-13',
    video: false,
    vote_average: 6.532,
    vote_count: 349,
  },
  {
    backdrop_path: '/tBmJCH9llj1Q9jDOS7vGWnl7GVj.jpg',
    id: 1209288,
    original_title: 'Justice League: Crisis on Infinite Earths Part Two',
    overview:
      'An endless army of shadow demons bent on the destruction of all reality swarms over our world and all parallel Earths! The only thing opposing them is the mightiest team of metahumans ever assembled. But not even the combined power of Superman, Batman, Wonder Woman, Green Lantern and all their fellow superheroes can slow down the onslaught of this invincible horde. What mysterious force is driving them? And how do the long-buried secrets of the Monitor and Supergirl threaten to crush our last defense?',
    poster_path: '/g8ak4QAGLZpqMs3CpnFHWWfIzJQ.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Justice League: Crisis on Infinite Earths Part Two',
    original_language: 'en',
    genre_ids: [16, 878, 28],
    popularity: 790.506,
    release_date: '2024-04-22',
    video: false,
    vote_average: 6.216,
    vote_count: 37,
  },
  {
    backdrop_path: '/4yrOyO3N55XazHQXXYoqiiPQd40.jpg',
    id: 938614,
    original_title: 'Late Night with the Devil',
    overview:
      "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
    poster_path: '/u3YQJctMzFN2wAvnkmXy41bXhFv.jpg',
    media_type: 'movie',
    adult: false,
    title: 'Late Night with the Devil',
    original_language: 'en',
    genre_ids: [27],
    popularity: 810.306,
    release_date: '2024-03-19',
    video: false,
    vote_average: 7.301,
    vote_count: 246,
  },
];

export const MOCK_PERSON_CREDITS = {
  cast: [
    {
      adult: false,
      backdrop_path: '/CoaYt6O54sMf3I8nKINsbjpDar.jpg',
      genre_ids: [27],
      id: 34592,
      original_language: 'en',
      original_title: 'ZMD: Zombies of Mass Destruction',
      overview:
        'An idyllic island town is under attack by that most invasive of pests: zombies! Port Gamble is being overrun with braineaters, and the people seem powerless to stave them off. But wait, a rag tag band of rebels is trying to turn the tide and push the invading hordes of undead back.',
      popularity: 8.012,
      poster_path: '/3K80OoyUb93qhx5jMUsNuKlV3IT.jpg',
      release_date: '2010-01-29',
      title: 'ZMD: Zombies of Mass Destruction',
      video: false,
      vote_average: 5.1,
      vote_count: 77,
      character: 'Lisa',
      credit_id: '52fe456d9251416c91031ff9',
      order: 19,
    },
    {
      adult: false,
      backdrop_path: '/qrcS0uQYNZrMdf0sOSN7Wt454fm.jpg',
      genre_ids: [27, 9648],
      id: 45657,
      original_language: 'en',
      original_title: 'The Ward',
      overview:
        "Kristen, a troubled young woman, is captured by the police after burning down a farmhouse and is locked in the North Bend Psychiatric Hospital. Soon, she begins to suspect that the place has a dark secret at its core and she's determined to find out what it is.",
      popularity: 14.114,
      poster_path: '/x2dqoY5cYop46SKebNXRNL5EXEM.jpg',
      release_date: '2010-09-13',
      title: 'The Ward',
      video: false,
      vote_average: 5.795,
      vote_count: 1151,
      character: 'Young Alice Hudson',
      credit_id: '52fe46cdc3a36847f8112f9d',
      order: 7,
    },
    {
      adult: false,
      backdrop_path: '/A6IR6fgE6OvYKWuDeE1rDnLmeef.jpg',
      genre_ids: [18, 80, 10770],
      id: 357525,
      original_language: 'en',
      original_title: 'Stolen from the Suburbs',
      overview:
        'A single mother from the suburbs searches for her kidnapped daughter before human traffickers sell her on the international market.',
      popularity: 5.871,
      poster_path: '/2jU6kQzIo9IiT1NJMtp9aKTj8I9.jpg',
      release_date: '2015-08-30',
      title: 'Stolen from the Suburbs',
      video: true,
      vote_average: 6.3,
      vote_count: 23,
      character: 'Emma',
      credit_id: '56f84f099251414c3200084f',
      order: 2,
    },
    {
      adult: false,
      backdrop_path: '/ltKOlYoilem816Y4d41W4PipHQb.jpg',
      genre_ids: [53, 27, 18],
      id: 409056,
      original_language: 'en',
      original_title: 'Along Came the Devil',
      overview:
        'After a troubled childhood, Ashley searches for a connection, and unknowingly invites in a demonic force, which leaves her loved ones fighting for her soul.',
      popularity: 9.662,
      poster_path: '/tEiu83QxMMWWD8gWUtXR4piF1Iw.jpg',
      release_date: '2018-08-10',
      title: 'Along Came the Devil',
      video: false,
      vote_average: 5.8,
      vote_count: 76,
      character: 'Ashley',
      credit_id: '579e350c92514177f5001e31',
      order: 3,
    },
    {
      adult: false,
      backdrop_path: '/cbiiobXlsliG4x7KNMJV9yw6zLC.jpg',
      genre_ids: [18, 53],
      id: 384446,
      original_language: 'en',
      original_title: 'Cassidy Way',
      overview:
        "When a film student and her two friends go to Kern County to shoot a documentary, they stumble upon a mysterious family and learn why Pandora's box should never have been opened.",
      popularity: 1.276,
      poster_path: '/c8Ua7LFit8jt7vQuIHZQbNe7uIZ.jpg',
      release_date: '2016-02-23',
      title: 'Cassidy Way',
      video: false,
      vote_average: 3.7,
      vote_count: 8,
      character: 'Kelsey Connors',
      credit_id: '57ae62ac9251412f45000c09',
      order: 4,
    },
    {
      adult: false,
      backdrop_path: '/xtbgphlQvHQEfxH23e08vnYzrYd.jpg',
      genre_ids: [28, 18, 10751],
      id: 316822,
      original_language: 'en',
      original_title: 'The Martial Arts Kid',
      overview:
        'When a troubled teen from Cleveland experiences bullying in Cocoa Beach, he soon learns Martial Arts to gain confidence and self-defense skills.',
      popularity: 2.238,
      poster_path: '/9MaPHFNj2ljX0Xk76eG0cjvN2dd.jpg',
      release_date: '2015-04-11',
      title: 'The Martial Arts Kid',
      video: false,
      vote_average: 6.8,
      vote_count: 6,
      character: 'Julia',
      credit_id: '57ae653fc3a368030a000f1e',
      order: 7,
    },
    {
      adult: false,
      backdrop_path: '/rhATinMhgKwBxsuS5OcFaaCSuuB.jpg',
      genre_ids: [28, 27],
      id: 395797,
      original_language: 'en',
      original_title: 'The Horde',
      overview:
        'The film follows John Crenshaw as he accompanies his girlfriend and her students on a weekend nature-photography expedition deep into the woods. What should be an educational and fun-filled weekend turns into horror as the group is besieged by an unspeakable evil - a horde of hideously disfigured, mutated humans with an insatiable taste for blood. As things go from bad to worse, Crenshaw becomes their only hope if they are going to get out alive.',
      popularity: 7.716,
      poster_path: '/mHjXFWi5WnW2idcsOUC0zfAXvQd.jpg',
      release_date: '2016-05-06',
      title: 'The Horde',
      video: false,
      vote_average: 4.9,
      vote_count: 48,
      character: 'Hailey Summers',
      credit_id: '57ae63d69251412f40000d1b',
      order: 5,
    },
    {
      adult: false,
      backdrop_path: '/tOWjPR2PO8ujUhQxK4JPU0D0KmD.jpg',
      genre_ids: [18, 10770, 80],
      id: 116853,
      original_language: 'en',
      original_title: 'The Bling Ring',
      overview:
        "At the center of one of Hollywood's most notorious burglary rings in 2009 was a group of average, middle-class teens from a quiet suburb. This is the behind-the-scenes story of how Nick, a shy, awkward boy, lured by the promise of popularity and acceptance, found himself following his glamorous, charismatic best friend Rachel into breaking into celebrities' houses and robbing them of millions of dollars in clothes and jewelry.",
      popularity: 6.014,
      poster_path: '/x3WmMVULbz2IZ75J3n5wWaatRml.jpg',
      release_date: '2011-09-26',
      title: 'The Bling Ring',
      video: false,
      vote_average: 4.7,
      vote_count: 45,
      character: 'Izzy Fishman',
      credit_id: '57d502e9c3a3680b9f005099',
      order: 14,
    },
    {
      adult: false,
      backdrop_path: '/44dgugY6wBUFfJdaVOhNfr6E5g3.jpg',
      genre_ids: [80, 18, 9648],
      id: 396461,
      original_language: 'en',
      original_title: 'Under the Silver Lake',
      overview:
        "Young and disenchanted Sam meets a mysterious and beautiful woman who's swimming in his building's pool one night. When she suddenly vanishes the next morning, Sam embarks on a surreal quest across Los Angeles to decode the secret behind her disappearance, leading him into the murkiest depths of mystery, scandal and conspiracy.",
      popularity: 19.151,
      poster_path: '/cJ9aKlEgTLYtpYjNqin06YqJRUl.jpg',
      release_date: '2018-06-21',
      title: 'Under the Silver Lake',
      video: false,
      vote_average: 6.393,
      vote_count: 1297,
      character: 'Shooting Star #2',
      credit_id: '582bf8e4c3a36872c600452d',
      order: 27,
    },
    {
      adult: false,
      backdrop_path: '/tq1o96WpaQ3i3JkFU1WDl0AiCo1.jpg',
      genre_ids: [10749, 35],
      id: 472840,
      original_language: 'en',
      original_title: 'Vikes',
      overview:
        'High school kid, Thorvald, embarks on an effort to change the name of his school\'s sports and academic teams from the "Vikings", to something less offensive to Norwegians. It\'s a love story.',
      popularity: 3.878,
      poster_path: '/8rmtrpAkKOpUqn1aHLBnPbMIAFk.jpg',
      release_date: '2017-08-26',
      title: 'Vikes',
      video: false,
      vote_average: 6.3,
      vote_count: 7,
      character: 'Ida',
      credit_id: '59a3555ec3a36847c504eead',
      order: 1,
    },
    {
      adult: false,
      backdrop_path: '/2OXuxD5nJ141hMZWw7IFFNhw4YV.jpg',
      genre_ids: [53],
      id: 503420,
      original_language: 'en',
      original_title: 'Relentless',
      overview:
        'An American mother searches for her daughter who was kidnapped by human traffickers in Central America.',
      popularity: 5.349,
      poster_path: '/6uHwUC7bOlD5kvfCGJX8hEBCEyP.jpg',
      release_date: '2018-02-06',
      title: 'Relentless',
      video: false,
      vote_average: 4.4,
      vote_count: 20,
      character: 'Ally Drew',
      credit_id: '5a79b046c3a3682265025210',
      order: 4,
    },
    {
      adult: false,
      backdrop_path: '/aybN9RlejO1tIrvqw6qb1d8BNuA.jpg',
      genre_ids: [35, 18],
      id: 255454,
      original_language: 'en',
      original_title: 'Angels in Stardust',
      overview:
        'An imaginative teenage girl, living in a mystical and dangerous community built on a deserted drive-in movie lot along the Texas/Oklahoma border, struggles to realize her potential, and escape the world she was born into.',
      popularity: 3.305,
      poster_path: '/6G0LLoIh3G9sJUveBTC5aCSTLKe.jpg',
      release_date: '2014-02-21',
      title: 'Angels in Stardust',
      video: false,
      vote_average: 5.6,
      vote_count: 16,
      character: 'Annie',
      credit_id: '5a8a5233925141759906d726',
      order: 12,
    },
    {
      adult: false,
      backdrop_path: '/sUnAK6VaypBQAMrYa9XU8tGcp9X.jpg',
      genre_ids: [35, 27],
      id: 480923,
      original_language: 'en',
      original_title: 'Dead Ant',
      overview:
        'When the 1989 "one-hit-wonder" glam-metal band "Sonic Grave" embark on a trip to Coachella in hopes of a comeback, their peyote trip pit stop in Joshua Tree incites an "unworldly" viscous attack, and they must "rock" themselves out of harms way.',
      popularity: 5.094,
      poster_path: '/2NoqvEpApbcnSWFpbHAswOYufSQ.jpg',
      release_date: '2017-10-10',
      title: 'Dead Ant',
      video: false,
      vote_average: 5.1,
      vote_count: 52,
      character: 'Sam',
      credit_id: '5a8a527b9251410aae06f16f',
      order: 5,
    },
    {
      adult: false,
      backdrop_path: '/9RFXPgdcWLQyBnfd7rPBsGXhUYw.jpg',
      genre_ids: [878, 53],
      id: 164331,
      original_language: 'en',
      original_title: 'Spiders',
      overview:
        'After a Soviet space station crashes into a New York City subway tunnel, a species of venomous spiders is discovered, and soon they mutate to gigantic proportions and wreak havoc on the city.',
      popularity: 12.076,
      poster_path: '/vuF1EopyrrtRvVPsAsFBAThcWIT.jpg',
      release_date: '2013-02-08',
      title: 'Spiders',
      video: false,
      vote_average: 4.4,
      vote_count: 155,
      character: 'Emily',
      credit_id: '5a8a5260c3a36862e1070ef6',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 523772,
      original_language: 'en',
      original_title: 'Manic',
      overview:
        'An Ivy-­league bound, overachieving teen is derailed after a manic episode lands her in a school for kids with mental illness.',
      popularity: 1.008,
      poster_path: '/qHJBTHULZLHKrsWCqBrBkOs0Y3h.jpg',
      release_date: '2017-04-23',
      title: 'Manic',
      video: false,
      vote_average: 10,
      vote_count: 1,
      character: "Missy 'Paper Girl'",
      credit_id: '5af5e75ec3a36811a9001c48',
      order: 1,
    },
    {
      adult: false,
      backdrop_path: '/2DwSRqFuqZoGqbJVkuAFsulYVQA.jpg',
      genre_ids: [35],
      id: 539617,
      original_language: 'en',
      original_title: 'Big Time Adolescence',
      overview:
        'A seemingly bright and mostly innocent 16-year-old named Mo attempts to navigate high school under the guidance of his best friend Zeke, an unmotivated-yet-charismatic college dropout. Although Zeke genuinely cares about Mo, things start to go awry as he teaches Mo nontraditional life lessons in drug dealing, partying, and dating. Meanwhile, Mo’s well-meaning dad tries to step in and take back the reins of his son’s upbringing.',
      popularity: 11.161,
      poster_path: '/bFjhHlHjiWouLmJWxGMHGn1MQKX.jpg',
      release_date: '2020-03-13',
      title: 'Big Time Adolescence',
      video: false,
      vote_average: 7.311,
      vote_count: 322,
      character: 'Holly',
      credit_id: '5b61321f925141406800c4a7',
      order: 3,
    },
    {
      adult: false,
      backdrop_path: '/cD06ZGiDxK9nDWobvi11RVKM8tS.jpg',
      genre_ids: [10770, 53, 80],
      id: 522915,
      original_language: 'en',
      original_title: 'The Wrong Daughter',
      overview:
        "Kate and Joe have longed to be parents and are considering in vitro options... when Danica, a child Kate gave up 17 years ago, appears on Facebook. Danica comes to live with them, but she's not their real child. She's an impostor who will do anything, even kill, to get the mother's love she never had.",
      popularity: 10.77,
      poster_path: '/16KYr5PHbnjrDiReeAuj2xbJIrX.jpg',
      release_date: '2018-04-15',
      title: 'The Wrong Daughter',
      video: false,
      vote_average: 5.9,
      vote_count: 24,
      character: 'Samantha',
      credit_id: '5b612fa40e0a267ef100d01b',
      order: 2,
    },
    {
      adult: false,
      backdrop_path: '/oRiUKwDpcqDdoLwPoA4FIRh3hqY.jpg',
      genre_ids: [35, 18, 53],
      id: 466272,
      original_language: 'en',
      original_title: 'Once Upon a Time... in Hollywood',
      overview:
        'Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…',
      popularity: 62.238,
      poster_path: '/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg',
      release_date: '2019-07-24',
      title: 'Once Upon a Time... in Hollywood',
      video: false,
      vote_average: 7.439,
      vote_count: 12799,
      character: "'Snake'",
      credit_id: '5b8526ef92514159ce04d275',
      order: 26,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 577901,
      original_language: 'en',
      original_title: 'Love Made Visible',
      overview:
        "A 16-year-old girl is brought to a house by a lawyer and told that this house belongs to her dad who she hasn't seen in 14 years. Strangely, she was told by her late mum that her dad died in a car accident a long time ago. From not accepting her dad to once again bonding with him again, what happened? What happened 14 years ago?",
      popularity: 1.13,
      poster_path: '/7bsbpql0kdQmCo7CYIzTAZ5oTSr.jpg',
      release_date: '2015-01-22',
      title: 'Love Made Visible',
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: 'Leah',
      credit_id: '5c4b8018c3a36847828e1cf7',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: '/ha4BwLJMntYhzgldjB5WpVYuETO.jpg',
      genre_ids: [18],
      id: 586456,
      original_language: 'en',
      original_title: 'Clementine',
      overview:
        'Reeling from a one-sided breakup, heartbroken Karen breaks into her ex’s lakehouse. There, she strikes up a complicated relationship with provocative younger woman Lana.',
      popularity: 4.689,
      poster_path: '/kcA4oFfMAk7plwFDogL0evll8L5.jpg',
      release_date: '2019-04-27',
      title: 'Clementine',
      video: false,
      vote_average: 4.9,
      vote_count: 33,
      character: 'Lana',
      credit_id: '5c7ee068c3a3684e8fd276d9',
      order: 1,
    },
    {
      adult: false,
      backdrop_path: '/zwB70O5riBoGEvAE2SAQ9Y6K4rN.jpg',
      genre_ids: [27, 9648, 53, 10402],
      id: 643550,
      original_language: 'en',
      original_title: 'Nocturne',
      overview:
        'Inside the halls of an elite arts academy, a timid music student begins to outshine her more accomplished and outgoing twin sister when she discovers a mysterious notebook belonging to a recently deceased classmate.',
      popularity: 12.072,
      poster_path: '/zJNFiWBGYSMbfTAk6Ygqdj6Rahq.jpg',
      release_date: '2020-10-13',
      title: 'Nocturne',
      video: false,
      vote_average: 5.898,
      vote_count: 406,
      character: 'Juliet Lowe',
      credit_id: '5db87d2da1d3320014e7c836',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: '/3rwszCm4XyBtIWSjbUbgNwJOidu.jpg',
      genre_ids: [53],
      id: 645710,
      original_language: 'en',
      original_title: 'The Voyeurs',
      overview:
        'When Pippa and Thomas move into their dream apartment, they notice that their windows look directly into the apartment opposite – inviting them to witness the volatile relationship of the attractive couple across the street. But what starts as a simple curiosity turns into full-blown obsession with increasingly dangerous consequences.',
      popularity: 37.938,
      poster_path: '/8Y4XOIWhpOvSOEn8XrxbkH9yAXO.jpg',
      release_date: '2021-08-25',
      title: 'The Voyeurs',
      video: false,
      vote_average: 6.649,
      vote_count: 785,
      character: 'Pippa',
      credit_id: '5dc2b15e9d89390018337194',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 755899,
      original_language: 'en',
      original_title: 'The Opium Eater',
      overview:
        'A coat-and-tie-wearing social worker scours the countryside in search of wild opium poppies.',
      popularity: 1.4,
      poster_path: '/yBKexc6VQrD9HqgfLb5a31jx3JW.jpg',
      release_date: '2010-12-10',
      title: 'The Opium Eater',
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: 'Sara Detzer',
      credit_id: '5f9052d4c048a9003841f547',
      order: 5,
    },
    {
      adult: false,
      backdrop_path: '/a7pGifLdzNvkzFxSyrvte3PQoZS.jpg',
      genre_ids: [18, 10402, 10749],
      id: 750459,
      original_language: 'en',
      original_title: 'Downfalls High',
      overview:
        'When reserved and lonely teenager Fenix meets popular high school girl Scarlett, the two form a bond that shapes the rest of his life.',
      popularity: 8.184,
      poster_path: '/sm9SqRIKHgIvj4YZn84ybvlfco1.jpg',
      release_date: '2021-01-15',
      title: 'Downfalls High',
      video: false,
      vote_average: 6.3,
      vote_count: 40,
      character: 'Scarlett Smith',
      credit_id: '5fbc461b8c7b0f003d077776',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: '/xmqXQOGxFaUCZr9wXrD2WD2V3aT.jpg',
      genre_ids: [27, 53, 28],
      id: 669671,
      original_language: 'en',
      original_title: 'Night Teeth',
      overview:
        'A college student moonlighting as a chauffeur picks up two mysterious women for a night of party-hopping across LA. But when he uncovers their bloodthirsty intentions—and their dangerous, shadowy underworld—he must fight to stay alive.',
      popularity: 34.848,
      poster_path: '/4niEFGAUEz3GUqwk9Y2y4aAERhE.jpg',
      release_date: '2021-10-20',
      title: 'Night Teeth',
      video: false,
      vote_average: 6.426,
      vote_count: 738,
      character: 'Eva',
      credit_id: '5fbedde257530e003f3c37be',
      order: 5,
    },
    {
      adult: false,
      backdrop_path: '/ice3dNrgJZmyFXs4InhjAJMIGMS.jpg',
      genre_ids: [28, 35, 80],
      id: 934456,
      original_language: 'en',
      original_title: 'Americana',
      overview:
        'When a rare Lakota Ghost Shirt falls into the black market in a small town in South Dakota, the lives of local outsiders and outcasts violently intertwine.',
      popularity: 5.336,
      poster_path: '/dd5Ko8z4qkzucIc2hVmQslfBGVq.jpg',
      release_date: '2023-03-17',
      title: 'Americana',
      video: false,
      vote_average: 10,
      vote_count: 2,
      character: 'Penny Jo Poplin',
      credit_id: '61fc20d2fe6c1800f43ace66',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: '/pwGmXVKUgKN13psUjlhC9zBcq1o.jpg',
      genre_ids: [28, 14],
      id: 634492,
      original_language: 'en',
      original_title: 'Madame Web',
      overview:
        'Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.',
      popularity: 1928.87,
      poster_path: '/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg',
      release_date: '2024-02-14',
      title: 'Madame Web',
      video: false,
      vote_average: 5.643,
      vote_count: 906,
      character: 'Julia Cornwall',
      credit_id: '623224460582240045b30c3a',
      order: 1,
    },
    {
      adult: false,
      backdrop_path: '/7CSILt4l54Kxsk0DzQTYPq9WojO.jpg',
      genre_ids: [18, 53],
      id: 985617,
      original_language: 'en',
      original_title: 'Reality',
      overview:
        'Augusta, Georgia, United States, June 3, 2017. After running some errands, Reality Winner returns home, where she is approached by two men.',
      popularity: 33.524,
      poster_path: '/rTEYxSDo9aJTTbM0zuMMLgzJcUJ.jpg',
      release_date: '2023-06-02',
      title: 'Reality',
      video: false,
      vote_average: 6.443,
      vote_count: 297,
      character: 'Reality Winner',
      credit_id: '62a0fb3a7d5db5086bf35255',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 1018396,
      original_language: 'en',
      original_title: 'The Registration',
      overview:
        "Imagine it’s legal to commit one murder in your lifetime–if you Register the victim and accomplish the kill within fourteen days. So when Lynell Mize stands in line to Register the man who abused her as a child, she’s shocked to hear a stranger registered her to be killed. Why would anyone who doesn't know her squander his one legal murder on her? Desperate to survive the next two weeks, she must find out who wants to kill her–and why.",
      popularity: 2.862,
      poster_path: '/gG3bxDZPYElkMgApEx77e8wzdkf.jpg',
      release_date: '',
      title: 'The Registration',
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: 'Lynell Mize',
      credit_id: '630d0feb724de10083a21542',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1034482,
      original_language: 'en',
      original_title: 'Barbarella',
      overview:
        'A remake of the 1968 classic, based on the comic books by Jean-Claude Forest. Barbarella, an astronaut from the 41st century, sets out to find and stop the evil scientist Durand Durand, whose Positronic Ray threatens to bring evil back into the galaxy.',
      popularity: 2.065,
      poster_path: '/kOIVwpDSlLQxJzuBXQFvqdIEYjd.jpg',
      release_date: '',
      title: 'Barbarella',
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: 'Barbarella',
      credit_id: '634603a11b7c590079198f5e',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [53],
      id: 1034721,
      original_language: 'en',
      original_title: 'The Caretaker',
      overview:
        'A young woman accepts a caretaking job on Craigslist and quickly discovers her responsibilities have stakes far greater (and more dangerous) than she could have ever imagined.',
      popularity: 1.396,
      poster_path: null,
      release_date: '',
      title: 'The Caretaker',
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: '',
      credit_id: '6346ed8d5b4fed0091da50bb',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: '/wCoRlQy7TmeM3jDFsLX1cJepjJG.jpg',
      genre_ids: [27, 9648, 53],
      id: 1041613,
      original_language: 'en',
      original_title: 'Immaculate',
      overview:
        'Cecilia, an American nun of devout faith, embarks on a new journey in a remote convent in the picturesque Italian countryside. Cecilia’s warm welcome quickly devolves into a nightmare as it becomes clear her new home harbors a sinister secret and unspeakable horrors.',
      popularity: 109.845,
      poster_path: '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg',
      release_date: '2024-03-20',
      title: 'Immaculate',
      video: false,
      vote_average: 6.2,
      vote_count: 56,
      character: 'Cecilia',
      credit_id: '635c4b87e263bb00799e505d',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
      genre_ids: [10749, 35],
      id: 1072790,
      original_language: 'en',
      original_title: 'Anyone But You',
      overview:
        'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
      popularity: 545.91,
      poster_path: '/5qHoazZiaLe7oFBok7XlUhg96f2.jpg',
      release_date: '2023-12-21',
      title: 'Anyone But You',
      video: false,
      vote_average: 7.068,
      vote_count: 1220,
      character: 'Bea',
      credit_id: '63bf14f4df857c0089269b1a',
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18, 53],
      id: 1097311,
      original_language: 'en',
      original_title: 'Echo Valley',
      overview:
        'Reeling from a personal tragedy, Kate spends her days boarding and training horses at Echo Valley Farm, twenty-two secluded, picturesque acres in Southeastern Pennsylvania. Late one night, her wayward daughter Claire arrives on her doorstep, frightened, trembling — and covered in someone else’s blood.',
      popularity: 0.989,
      poster_path: null,
      release_date: '',
      title: 'Echo Valley',
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: 'Claire',
      credit_id: '6408cfa89f51af1d52ce1ebf',
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [53],
      id: 1042834,
      original_language: 'en',
      original_title: 'Eden',
      overview:
        'A darkly comic tale of murder and survival, focusing on an eclectic group of characters who abandon civilization for the Galápagos Islands. They are all searching for the answer to that ever-pressing question that plagues us all: what is the meaning of life?',
      popularity: 3.367,
      poster_path: null,
      release_date: '',
      title: 'Eden',
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: '',
      credit_id: '653fc9d4109cd0014df5c06e',
      order: 5,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [27],
      id: 517559,
      original_language: 'en',
      original_title: 'The Chattering',
      overview:
        'Hundreds of gremlin-like mutant creatures from a melting glacier violently descend on a survivalist cabin in the mountains where an unsuspecting circle of high school seniors are celebrating their last weekend together before college.',
      popularity: 1.69,
      poster_path: '/jp99v4SPIE0B7G6jOLtqCNCLW4i.jpg',
      release_date: '2017-10-31',
      title: 'The Chattering',
      video: false,
      vote_average: 0,
      vote_count: 0,
      character: 'Ashely',
      credit_id: '656f26b73dc31300c4fb35e1',
      order: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18, 10749, 53],
      id: 1259849,
      original_language: 'en',
      original_title: 'It Happened Again Last Night',
      overview: 'Paige must choose between love and fear before she has no choices left to make.',
      popularity: 1.371,
      poster_path: '/76T7HmxloMZxZyGLDo6sUAbEHgU.jpg',
      release_date: '2017-12-10',
      title: 'It Happened Again Last Night',
      video: false,
      vote_average: 6,
      vote_count: 1,
      character: 'Young Paige',
      credit_id: '65f4d5a259e8a90163190a01',
      order: 0,
    },
  ],
  crew: [
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 1018396,
      original_language: 'en',
      original_title: 'The Registration',
      overview:
        "Imagine it’s legal to commit one murder in your lifetime–if you Register the victim and accomplish the kill within fourteen days. So when Lynell Mize stands in line to Register the man who abused her as a child, she’s shocked to hear a stranger registered her to be killed. Why would anyone who doesn't know her squander his one legal murder on her? Desperate to survive the next two weeks, she must find out who wants to kill her–and why.",
      popularity: 2.862,
      poster_path: '/gG3bxDZPYElkMgApEx77e8wzdkf.jpg',
      release_date: '',
      title: 'The Registration',
      video: false,
      vote_average: 0,
      vote_count: 0,
      credit_id: '630d1017924ce60091364a9f',
      department: 'Production',
      job: 'Producer',
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1034482,
      original_language: 'en',
      original_title: 'Barbarella',
      overview:
        'A remake of the 1968 classic, based on the comic books by Jean-Claude Forest. Barbarella, an astronaut from the 41st century, sets out to find and stop the evil scientist Durand Durand, whose Positronic Ray threatens to bring evil back into the galaxy.',
      popularity: 2.065,
      poster_path: '/kOIVwpDSlLQxJzuBXQFvqdIEYjd.jpg',
      release_date: '',
      title: 'Barbarella',
      video: false,
      vote_average: 0,
      vote_count: 0,
      credit_id: '634611b81b7c590081c0c55e',
      department: 'Production',
      job: 'Executive Producer',
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [53],
      id: 1034721,
      original_language: 'en',
      original_title: 'The Caretaker',
      overview:
        'A young woman accepts a caretaking job on Craigslist and quickly discovers her responsibilities have stakes far greater (and more dangerous) than she could have ever imagined.',
      popularity: 1.396,
      poster_path: null,
      release_date: '',
      title: 'The Caretaker',
      video: false,
      vote_average: 0,
      vote_count: 0,
      credit_id: '6346edb11b7c59007e6f2674',
      department: 'Production',
      job: 'Producer',
    },
    {
      adult: false,
      backdrop_path: '/wCoRlQy7TmeM3jDFsLX1cJepjJG.jpg',
      genre_ids: [27, 9648, 53],
      id: 1041613,
      original_language: 'en',
      original_title: 'Immaculate',
      overview:
        'Cecilia, an American nun of devout faith, embarks on a new journey in a remote convent in the picturesque Italian countryside. Cecilia’s warm welcome quickly devolves into a nightmare as it becomes clear her new home harbors a sinister secret and unspeakable horrors.',
      popularity: 109.845,
      poster_path: '/fdZpvODTX5wwkD0ikZNaClE4AoW.jpg',
      release_date: '2024-03-20',
      title: 'Immaculate',
      video: false,
      vote_average: 6.2,
      vote_count: 56,
      credit_id: '635c4bd0b3316b00790c030f',
      department: 'Production',
      job: 'Producer',
    },
    {
      adult: false,
      backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
      genre_ids: [10749, 35],
      id: 1072790,
      original_language: 'en',
      original_title: 'Anyone But You',
      overview:
        'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
      popularity: 545.91,
      poster_path: '/5qHoazZiaLe7oFBok7XlUhg96f2.jpg',
      release_date: '2023-12-21',
      title: 'Anyone But You',
      video: false,
      vote_average: 7.068,
      vote_count: 1220,
      credit_id: '63bf165ee16e5a007ea9159e',
      department: 'Production',
      job: 'Executive Producer',
    },
  ],
  id: 115440,
};

export const MOCK_PERSON = {
  page: 1,
  results: [
    {
      adult: false,
      gender: 1,
      id: 115440,
      known_for_department: 'Acting',
      name: 'Sydney Sweeney',
      original_name: 'Sydney Sweeney',
      popularity: 20.664,
      profile_path: '/qYiaSl0Eb7G3VaxOg8PxExCFwon.jpg',
      known_for: [
        {
          adult: false,
          backdrop_path: '/9KnIzPCv9XpWA0MqmwiKBZvV1Sj.jpg',
          id: 85552,
          name: 'Euphoria',
          original_language: 'en',
          original_name: 'Euphoria',
          overview:
            'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.',
          poster_path: '/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg',
          media_type: 'tv',
          genre_ids: [18],
          popularity: 364.992,
          first_air_date: '2019-06-16',
          vote_average: 8.334,
          vote_count: 9381,
          origin_country: ['US'],
        },
        {
          adult: false,
          backdrop_path: '/nTPFkLUARmo1bYHfkfdNpRKgEOs.jpg',
          id: 1072790,
          title: 'Anyone But You',
          original_language: 'en',
          original_title: 'Anyone But You',
          overview:
            'After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.',
          poster_path: '/5qHoazZiaLe7oFBok7XlUhg96f2.jpg',
          media_type: 'movie',
          genre_ids: [10749, 35],
          popularity: 545.91,
          release_date: '2023-12-21',
          video: false,
          vote_average: 7.069,
          vote_count: 1218,
        },
        {
          adult: false,
          backdrop_path: '/3rwszCm4XyBtIWSjbUbgNwJOidu.jpg',
          id: 645710,
          title: 'The Voyeurs',
          original_language: 'en',
          original_title: 'The Voyeurs',
          overview:
            'When Pippa and Thomas move into their dream apartment, they notice that their windows look directly into the apartment opposite – inviting them to witness the volatile relationship of the attractive couple across the street. But what starts as a simple curiosity turns into full-blown obsession with increasingly dangerous consequences.',
          poster_path: '/8Y4XOIWhpOvSOEn8XrxbkH9yAXO.jpg',
          media_type: 'movie',
          genre_ids: [53],
          popularity: 37.938,
          release_date: '2021-08-25',
          video: false,
          vote_average: 6.65,
          vote_count: 784,
        },
      ],
    },
    {
      adult: false,
      gender: 0,
      id: 2131671,
      known_for_department: 'Acting',
      name: 'Sydney Sweeney',
      original_name: 'Sydney Sweeney',
      popularity: 0.6,
      profile_path: null,
      known_for: [
        {
          adult: false,
          backdrop_path: null,
          id: 748464,
          title: 'Yield',
          original_language: 'en',
          original_title: 'Yield',
          overview:
            "Yield is a horror film about a young couple on vacation who decides to go hiking in a national forest. It's only after they are inside that the couple begins to realize something is very wrong inside that forest.",
          poster_path: '/jEulrrxcsoXPUc1IQHMzzop4rCm.jpg',
          media_type: 'movie',
          genre_ids: [27],
          popularity: 0.6,
          release_date: '2020-05-29',
          video: false,
          vote_average: 3,
          vote_count: 1,
        },
        {
          adult: false,
          backdrop_path: '/rq1haR4TKfFZlB4EB3HtvB2vETJ.jpg',
          id: 1047193,
          title: 'Miami Rogue',
          original_language: 'en',
          original_title: 'Miami Rogue',
          overview:
            'Former champion boxer haunted by his past is recruited by ex-Fbi to rob drug cartels in this action love story in Miami Beach.',
          poster_path: '/fTK7RUJM27nOQ7LhrIZ84TYL3aP.jpg',
          media_type: 'movie',
          genre_ids: [28, 12, 10749],
          popularity: 0.6,
          release_date: '2019-07-27',
          video: false,
          vote_average: 0,
          vote_count: 0,
        },
      ],
    },
  ],
  total_pages: 1,
  total_results: 2,
};
